name: Azure Pipeline Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Azure Pipeline
    runs-on: windows-latest
    steps:
    - name: Run Azure Pipeline
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/v-2amitc/githubactionsproj'
        azure-pipeline-name: 'gtbactions'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}